*** Variables ***
${ANKLE}	Ankle
${ARMPITS}	Armpits
${BACK}		Back
${BELLY}	Belly
${BREAST}	Breast
${BUTTOCKS}		Buttocks
${EAR}		Ear
${ELBOW}		Elbow
${EYES}		Eyes
${FACE}		Face
${FEMALE}		Female
${FINGER}		Finger
${FOOT}		Foot
${FOREARM}		Forearm
${GENITALIA}	Genitalia
${GREETING}		Hello!
${HAND}		Hand
${HEAD}		Head
${HEEL}		Heel
${HIP}		Hip
${KNEE}		Knee
${LOWER_BACK}	Lower back
${LOWER_LEG}	Lower leg
${MALE}		Male
${MENTAL}	Mental
${MOUTH}	Mouth
${NAPE}		Nape
${NOSE}		Nose
${OCCIPUT}		Occiput
${SEARCH}		Search
${SHOULDER}		Shoulder
${SPINE}		Spine
${THIGHS}		Thighs
${THORAX}		Thorax
${THROAT}		Throat
${TOE}		Toe
${UPPER_ARM}		Upper arm
${WRIST}		Wrist
@{LIST_OF_ABDOMEN}    ${BELLY}		${BREAST}    ${THORAX}
@{LIST_OF_BACK}    ${BACK}    ${LOWER_BACK}    ${SPINE}
@{LIST_OF_HEAD_BACK}    ${NAPE}    ${OCCIPUT}
@{LIST_OF_HEAD_FRONT}    ${EAR}    ${EYES}    ${FACE}    ${HEAD}    ${MENTAL}    ${MOUTH}    ${NOSE}    ${THROAT}
@{LIST_OF_HIPS}    ${GENITALIA}    ${HIP}
@{LIST_OF_LEGS}    ${ANKLE}    ${FOOT}    ${HEEL}    ${KNEE}    ${LOWER_LEG}    ${THIGHS}    ${TOE}
@{LIST_OF_LOWER_ARM}    ${ELBOW}    ${FINGER}    ${FOREARM}    ${HAND}    ${WRIST}
@{LIST_OF_LOWERBACK}    ${BUTTOCKS}    ${HIP}    ${LOWER_BACK}
@{LIST_OF_UPPER_ARM}    ${ARMPITS}    ${SHOULDER}    ${UPPER_ARM}
