*** Variables ***
${BTN_ON_ONE_SIDE}	On one side
${BTN_PULSATING_THROBBING}	Pulsating and throbbing
${BTN_YES}	Yes
${BTN_2_7_DAYS}		For 2-7 days
${BTN_24_HOURS}		For 24 hours
${BTN_ACCEPT}		Accept
${BTN_BACK}		Back
${BTN_CANCEL}	Cancel
${BTN_CHECK_FOR_ILLNESS}	Check for illness
${BTN_CONFIRM}		Confirm
${BTN_DO_NOT_ACCEPT}	I do not accept
${BTN_DOWNLOAD_REPORT}		Download report
${BTN_DULL_PRESSING}		Dull and pressing
${BTN_EDIT_ANSWER}		Edit answer
${BTN_EDIT_ANYWAY}		Edit anyway
${BTN_END_CHECK}		End check
${BTN_FEW_HOURS}		For a few hours
${BTN_FEW_MINUTES}	For a few minutes
${BTN_LONGER_THAN_A_WEEK}		Longer than 1 week
${BTN_MILD}		Mild
${BTN_MODERATE}		Moderate
${BTN_NO}		No
${BTN_NONE_SYMPTOMS}	None of these symptoms
${BTN_OKAY}		Okay
${BTN_ON_BOTH_SIDE}	On both sides
${BTN_RESTART}		Restart
${BTN_ROTATE}		Rotate
${BTN_SEVERE}		Severe
${BTN_SKIP}		Skip
${BTN_UNDERSTAND_SYMPTOMS}		Understand symptoms
${BTN_UNDERSTOOD}		I have understood