*** Variables ***
${I_CHECK_READY}	Your check is ready. Please note that this is not a medical diagnosis. If in doubt, you should always see a doctor.
${I_CHECK_SYMPTOMS}		Check your symptoms before proceeding
${I_FINAL_QUESTIONS}	Before we get to your results, I have some final questions regarding your health.
${I_FIRST_STEP}		As a first step, we will identify the symptom that bothers you the most.
${I_GENERAL_TERMS_TEXT}		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
${I_GENERAL_TERMS}		General Terms
${I_POSSIBLE_CAUSES}	Based on your check, the following causes are possible
${I_SUGGESTING_MORE_SYMPTOMS}		As a next step, I will suggest you more symptoms.