*** Variables ***
${Q_ADD_SYMPTOMS}		Do you want to add other symptoms?
${Q_COMPLAINT_FOR_LONGER_PERIOD}	Have you been suffering from such complaints regularly for a longer period of time?
${Q_HEADACHE_BEFORE}	Have you experienced similar headaches before?
${Q_HEADACHE_DESCRIPTION}		How would you describe your headache?
${Q_HEADACHE_DURATION}		For how long have you had a headache?
${Q_HEADACHE_SEVERITY}		How bad is your headache?
${Q_HEADACHE_SIDE}		Does your headache occur on one side of the head or both sides?
${Q_LAST_14_DAYS_COVID-19}		Are you aware that in the last 14 days you have had personal contact with a person suffering from COVID-19?
${Q_MAIN_SYMPTOMS}		Where do you experience your main symptom?
${Q_NECK_INJURY}		Did you suffer a head or neck injury before your symptoms appeared?
${Q_OTHER_SYMPTOMS}		Which other symptoms are you experiencing?
${Q_OVER_THE_COUNTER}		Do over-the-counter pain relievers help ease your discomfort?
${Q_SUFFERING_FROM_SPECIFIC_ILLNESS}		Would you like to understand the potential cause of certain symptoms or assess the possibility of suffering from a specific illness?
${Q_SYMPTOMS_EXPERIENCED}		Which symptom do you experience?
${Q_TIRED_AFTER_SMALL_EFFORT}		Do you feel inexplicably tired the next day after even a small effort?
${Q_WHAT_GENDER}		What is your biological gender?
${Q_WHAT_TO_DO_NEXT}		What would you like to do next?
${Q_YEAR_OF_BIRTH}		In which year were you born?